// Script:    testetabuleiro.script
// Autor:     Henrique Santiago
// Data:      20/abr/2014
// Propósito: Testar superficialmente o módulo tabuleiro

== Inicializar valores
=declararparm   tabuleiro0  int 0
=declararparm   tabuleiro1  int 1

=declararparm   colunaA    string  "a"
=declararparm   colunaB    string  "b"

=declararparm   pNULL          int  0
=declararparm   pNaoNULL       int  1


== Criar a tabuleiro 0
=criartabuleiro      tabuleiro0

== Inicializar tabuleiro0
=inicializartabuleiro  tabuleiro0

== Obter peca do tabuleiro0
=obterpeca    tabuleiro0   1 colunaA pNULL
=obterpeca    tabuleiro0   2 colunaA pNaoNULL
=obterpeca    tabuleiro0   1 colunaB pNaoNULL
=obterpeca    tabuleiro0   2 colunaB pNULL

=destruirtabuleiro   tabuleiro0

// fim
